spring:
  application:
    name: spring-jkube-external-config
  cloud:
    kubernetes:
      client:
        namespace: @project.artifactId@

management:
  endpoints:
    web:
      exposure:
        include: "*"

hello:
  greeting: Hello
