spring:
  application:
    name: spring-jkube-external-config
  cloud:
    kubernetes:
      client:
        namespace: @project.artifactId@

management:
  endpoint:
    env:
      show-values: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

hello:
  greeting: Hello
