name: Build and test

on:
  push:
    paths-ignore:
      - '.github/dependabot.yml'
      - '*.md'
    branches:
      - main
      - solution
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - '*.md'
      - '.github/dependabot.yml'
    branches:
      - main
      - solution
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  simple-build-test:
    runs-on: ubuntu-latest
    if: github.repository == 'RedHat-Middleware-Workshops/spring-jkube-external-config'
    strategy:
      fail-fast: false
      matrix:
        java:
          - '11'
          - '17'
    name: "build-test-java-${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: Run build Java ${{ matrix.java }}
        run: ./mvnw -B clean verify

  int-test:
    runs-on: ubuntu-latest
    needs: simple-build-test
    if: github.repository == 'RedHat-Middleware-Workshops/spring-jkube-external-config'
    strategy:
      fail-fast: false
      matrix:
        java:
          - '11'
          - '17'
    name: "int-test-java-${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Verify cluster available
        run: kubectl get pods -A

      - name: Deploy to minikube
        shell: bash
        run: |
          eval $(minikube -p minikube docker-env)
          ./mvnw -B clean k8s:deploy -Pk8s

      - name: Sleep for 30 seconds to wait for deployment
        shell: bash
        run: sleep 30s

      - name: Run integration tests
        shell: bash
        run: |
          export SERVICE_URL=$(minikube service spring-jkube-external-config --url)
          
          echo "Checking curl $SERVICE_URL/hello"
          [ "$(curl $SERVICE_URL/hello)" != "Hello (from Kubernetes ConfigMap) World" ] && exit -1
          
          echo "Checking curl $SERVICE_URL/hello/Yoda"
          [ "$(curl $SERVICE_URL/hello/Yoda)" != "Hello (from Kubernetes ConfigMap) Yoda" ] && exit -1