name: Build and test

on:
  push:
    paths-ignore:
      - '.github/dependabot.yml'
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - '.github/dependabot.yml'
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  simple-build-test:
    runs-on: ubuntu-latest
    if: github.repository == 'RedHat-Middleware-Workshops/spring-jkube-external-config'
    strategy:
      fail-fast: false
      matrix:
        java:
          - '11'
          - '17'
    name: "build-test-java-${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: Run build Java ${{ matrix.java }}
        run: ./mvnw -B clean verify