name: Build and test

on:
  push:
    paths-ignore:
      - '.github/dependabot.yml'
      - '*.md'
    branches:
      - solution
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - '*.md'
      - '.github/dependabot.yml'
    branches:
      - solution
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  simple-build-test:
    uses: RedHat-Middleware-Workshops/spring-jkube-external-config/.github/workflows/build-test.yml@main

  int-test:
    runs-on: ubuntu-latest
    needs: simple-build-test
    if: github.repository == 'RedHat-Middleware-Workshops/spring-jkube-external-config'
    strategy:
      fail-fast: false
      matrix:
        java:
          - '17'
    name: "int-test-java-${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: Setup Node.js (for newman)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install newman
        run: npm install -g newman

      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Verify cluster available
        id: verify-minikube-available
        run: kubectl get pods -A

      - name: Deploy to minikube
        shell: bash
        run: |
          eval $(minikube -p minikube docker-env)
          ./mvnw -B clean k8s:deploy -Pk8s -Dmaven.compiler.release=${{ matrix.java }}

      - name: Sleep for 30 seconds to wait for deployment
        shell: bash
        run: sleep 30s

      - name: Get app service url
        run: echo "SERVICE_URL=$(minikube service -n spring-jkube-external-config spring-jkube-external-config --url)" >> $GITHUB_ENV

      - name: Run integration tests
        working-directory: .github/workflows/postman
        run: newman run spring-jkube-external-config.postman_collection.json -e spring-jkube-external-config-kube.postman_environment.json --env-var SERVICE_URL=${{ env.SERVICE_URL }} --verbose

      - name: Tear down app
        if: steps.verify-minikube-available.outcome == 'success'
        run: |
          kubectl delete ns spring-jkube-external-config
          minikube stop
