name: Check PR against solution branch

on:
  workflow_call:
    inputs:
      pr_num:
        description: The PR Number
        required: true
        type: string
      pr_head_ref:
        description: The PR head ref
        required: true
        type: string
      java_version:
        description: The Java version
        required: true
        type: string
        default: '17'

defaults:
  run:
    shell: bash

jobs:
  check-commit-against-solution-branch:
    runs-on: ubuntu-latest
    if: github.repository == 'RedHat-Middleware-Workshops/spring-jkube-external-config'
    name: "check-commit-against-solution-branch-${{ inputs.java_version }}"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: solution
          path: src

      - name: Get PR diff
        run: wget ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/pull/${{ inputs.pr_num }}.diff

      - name: Apply change
        working-directory: src
        run: git apply --stat -v --ignore-whitespace --allow-empty --apply ../${{ inputs.pr_num }}.diff

      - name: Show diff
        working-directory: src
        run: git status && git diff

      - name: Setup Java ${{ inputs.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version }}
          distribution: temurin
          cache: maven

      - name: Run build and tests with Java ${{ inputs.java_version }}
        working-directory: src
        run: ./mvnw -B clean verify -Dmaven.compiler.release=${{ inputs.java_version }}