name: Check PR against solution branch

on:
  workflow_call:
    inputs:
      ref:
        description: The ref from the PR branch
        required: true
        type: string
      java_version:
        description: The Java version
        required: true
        type: string
        default: '17'

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  check-commit-against-solution-branch:
    runs-on: ubuntu-latest
    if: github.repository == 'RedHat-Middleware-Workshops/spring-jkube-external-config'
    name: "check-commit-against-solution-branch-${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v4
        ref: solution

      - name: Apply change
        run: git merge --squash --stat ${{ inputs.ref }}

      - name: Show diff
        run: git diff main

      - name: Setup Java ${{ inputs.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version }}
          distribution: temurin
          cache: maven

      - name: Run build and tests with Java ${{ inputs.java_version }}
        run: ./mvnw -B clean verify -Dmaven.compiler.release=${{ inputs.java_version }}